apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-loadgenerator
  labels:
    app: nginx-loadgenerator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-loadgenerator
  template:
    metadata:
      labels:
        app: nginx-loadgenerator
    spec:
      containers:
      - name: nginx-cont
        image: nginxinc/nginx-unprivileged
        ports:
        - containerPort: 80
        resources:
         limits:
           cpu: 300m
           memory: 200Mi
         requests:
           cpu: 150m
           memory: 100Mi
